// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mrtxmouhgeawskwbxyht.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1ydHhtb3VoZ2Vhd3Nrd2J4eWh0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMwMTA5MDYsImV4cCI6MjA2ODU4NjkwNn0.DQ036Kh2XKfPQS6c8gJ6K9f_ccs2W-7ybNQ4g99fU58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});